/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud.Client;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class ChunkTableUpdate : TypedRecordUpdate<Tuple<ChunkTable?, ChunkTable?>> { }

    public class ChunkTable : IMudTable
    {
        public readonly static TableId ID = new("", "Chunk");

        public override TableId GetTableId()
        {
            return ID;
        }

        public bool? completed;
        public long? mile;

        public override Type TableType()
        {
            return typeof(ChunkTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(ChunkTableUpdate);
        }

        public override void SetValues(params object[] functionParameters)
        {
            completed = (bool)functionParameters[0];

            mile = (long)(int)functionParameters[1];
        }

        public override bool SetValues(IEnumerable<Property> result)
        {
            var hasValues = false;
            foreach (var record in result)
            {
                var attribute = record["attribute"].ToString();
                var value = record["value"];

                switch (attribute)
                {
                    case "completed":
                        var completedValue = (bool)value;
                        completed = completedValue;
                        hasValues = true;
                        break;
                    case "mile":
                        var mileValue = (long)value;
                        mile = mileValue;
                        hasValues = true;
                        break;
                }
            }

            return hasValues;
        }

        public override IMudTable GetTableValue(string key)
        {
            var query = new Query()
                .Find("?value", "?attribute")
                .Where(TableId.ToString(), key, "?attribute", "?value");
            var result = NetworkManager.Instance.ds.Query(query);
            var chunkTable = new ChunkTable();
            var hasValues = false;

            foreach (var record in result)
            {
                var attribute = record["attribute"].ToString();
                var value = record["value"];

                switch (attribute)
                {
                    case "completed":
                        var completedValue = (bool)value;
                        chunkTable.completed = completedValue;
                        hasValues = true;
                        break;
                    case "mile":
                        var mileValue = (long)value;
                        chunkTable.mile = mileValue;
                        hasValues = true;
                        break;
                }
            }

            return hasValues ? chunkTable : null;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            ChunkTableUpdate update = (ChunkTableUpdate)tableUpdate;

            var currentValue = update?.TypedValue.Item1;
            if (currentValue == null)
            {
                Debug.LogError("No value on ChunkTable update");
            }

            return currentValue;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new ChunkTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<ChunkTable?, ChunkTable?> MapUpdates(Tuple<Property?, Property?> value)
        {
            ChunkTable? current = null;
            ChunkTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new ChunkTable
                    {
                        completed = value.Item1.TryGetValue("completed", out var completedVal)
                            ? (bool)completedVal
                            : default,
                        mile = value.Item1.TryGetValue("mile", out var mileVal)
                            ? (long)mileVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new ChunkTable { completed = null, mile = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new ChunkTable
                    {
                        completed = value.Item2.TryGetValue("completed", out var completedVal)
                            ? (bool)completedVal
                            : default,
                        mile = value.Item2.TryGetValue("mile", out var mileVal)
                            ? (long)mileVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new ChunkTable { completed = null, mile = null, };
                }
            }

            return new Tuple<ChunkTable?, ChunkTable?>(current, previous);
        }
    }
}
