/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud.Client;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class CoinageTableUpdate : TypedRecordUpdate<Tuple<CoinageTable?, CoinageTable?>> { }

    public class CoinageTable : IMudTable
    {
        public readonly static TableId ID = new("", "Coinage");

        public override TableId GetTableId()
        {
            return ID;
        }

        public long? value;

        public override Type TableType()
        {
            return typeof(CoinageTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(CoinageTableUpdate);
        }

        public override void SetValues(params object[] functionParameters)
        {
            value = (long)(int)functionParameters[0];
        }

        public override bool SetValues(IEnumerable<Property> result)
        {
            var hasValues = false;
            foreach (var record in result)
            {
                var attribute = record["attribute"].ToString();
                var value = record["value"];

                switch (attribute)
                {
                    case "value":
                        var valueValue = (long)value;
                        value = valueValue;
                        hasValues = true;
                        break;
                }
            }

            return hasValues;
        }

        public override IMudTable GetTableValue(string key)
        {
            var query = new Query()
                .Find("?value", "?attribute")
                .Where(TableId.ToString(), key, "?attribute", "?value");
            var result = NetworkManager.Instance.ds.Query(query);
            var coinageTable = new CoinageTable();
            var hasValues = false;

            foreach (var record in result)
            {
                var attribute = record["attribute"].ToString();
                var value = record["value"];

                switch (attribute)
                {
                    case "value":
                        var valueValue = (long)value;
                        coinageTable.value = valueValue;
                        hasValues = true;
                        break;
                }
            }

            return hasValues ? coinageTable : null;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            CoinageTableUpdate update = (CoinageTableUpdate)tableUpdate;
            return update?.TypedValue.Item1;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new CoinageTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<CoinageTable?, CoinageTable?> MapUpdates(
            Tuple<Property?, Property?> value
        )
        {
            CoinageTable? current = null;
            CoinageTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new CoinageTable
                    {
                        value = value.Item1.TryGetValue("value", out var valueVal)
                            ? (long)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new CoinageTable { value = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new CoinageTable
                    {
                        value = value.Item2.TryGetValue("value", out var valueVal)
                            ? (long)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new CoinageTable { value = null, };
                }
            }

            return new Tuple<CoinageTable?, CoinageTable?>(current, previous);
        }
    }
}
