/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class GameEventTableUpdate
        : TypedRecordUpdate<Tuple<GameEventTable?, GameEventTable?>> { }

    public class GameEventTable : IMudTable
    {
        public readonly static TableId ID = new("", "GameEvent");

        public override TableId GetTableId()
        {
            return ID;
        }

        public string? eventType;

        public override Type TableType()
        {
            return typeof(GameEventTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(GameEventTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            GameEventTable other = (GameEventTable)obj;

            if (other == null)
            {
                return false;
            }
            if (eventType != other.eventType)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            eventType = (string)functionParameters[0];
        }

        public override void RecordToTable(Record record)
        {
            var table = record.value;
            //bool hasValues = false;

            var eventTypeValue = (string)table["eventType"];
            eventType = eventTypeValue;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            GameEventTableUpdate update = (GameEventTableUpdate)tableUpdate;
            return update?.TypedValue.Item1;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new GameEventTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<GameEventTable?, GameEventTable?> MapUpdates(
            Tuple<Property?, Property?> value
        )
        {
            GameEventTable? current = null;
            GameEventTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new GameEventTable
                    {
                        eventType = value.Item1.TryGetValue("eventType", out var eventTypeVal)
                            ? (string)eventTypeVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new GameEventTable { eventType = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new GameEventTable
                    {
                        eventType = value.Item2.TryGetValue("eventType", out var eventTypeVal)
                            ? (string)eventTypeVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new GameEventTable { eventType = null, };
                }
            }

            return new Tuple<GameEventTable?, GameEventTable?>(current, previous);
        }
    }
}
