/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud.Client;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class GameStateTableUpdate
        : TypedRecordUpdate<Tuple<GameStateTable?, GameStateTable?>> { }

    public class GameStateTable : IMudTable
    {
        public readonly static TableId ID = new("", "GameState");

        public override TableId GetTableId()
        {
            return ID;
        }

        public long? miles;
        public long? playerCount;

        public override Type TableType()
        {
            return typeof(GameStateTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(GameStateTableUpdate);
        }

        public override void SetValues(params object[] functionParameters)
        {
            miles = (long)(int)functionParameters[0];

            playerCount = (long)(int)functionParameters[1];
        }

        public override bool SetValues(IEnumerable<Property> result)
        {
            var hasValues = false;
            foreach (var record in result)
            {
                var attribute = record["attribute"].ToString();
                var value = record["value"];

                switch (attribute)
                {
                    case "miles":
                        var milesValue = (long)value;
                        miles = milesValue;
                        hasValues = true;
                        break;
                    case "playerCount":
                        var playerCountValue = (long)value;
                        playerCount = playerCountValue;
                        hasValues = true;
                        break;
                }
            }

            return hasValues;
        }

        public override IMudTable GetTableValue(string key)
        {
            var query = new Query()
                .Find("?value", "?attribute")
                .Where(TableId.ToString(), key, "?attribute", "?value");
            var result = NetworkManager.Instance.ds.Query(query);
            var gameStateTable = new GameStateTable();
            var hasValues = false;

            foreach (var record in result)
            {
                var attribute = record["attribute"].ToString();
                var value = record["value"];

                switch (attribute)
                {
                    case "miles":
                        var milesValue = (long)value;
                        gameStateTable.miles = milesValue;
                        hasValues = true;
                        break;
                    case "playerCount":
                        var playerCountValue = (long)value;
                        gameStateTable.playerCount = playerCountValue;
                        hasValues = true;
                        break;
                }
            }

            return hasValues ? gameStateTable : null;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            GameStateTableUpdate update = (GameStateTableUpdate)tableUpdate;
            return update?.TypedValue.Item1;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new GameStateTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<GameStateTable?, GameStateTable?> MapUpdates(
            Tuple<Property?, Property?> value
        )
        {
            GameStateTable? current = null;
            GameStateTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new GameStateTable
                    {
                        miles = value.Item1.TryGetValue("miles", out var milesVal)
                            ? (long)milesVal
                            : default,
                        playerCount = value.Item1.TryGetValue("playerCount", out var playerCountVal)
                            ? (long)playerCountVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new GameStateTable { miles = null, playerCount = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new GameStateTable
                    {
                        miles = value.Item2.TryGetValue("miles", out var milesVal)
                            ? (long)milesVal
                            : default,
                        playerCount = value.Item2.TryGetValue("playerCount", out var playerCountVal)
                            ? (long)playerCountVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new GameStateTable { miles = null, playerCount = null, };
                }
            }

            return new Tuple<GameStateTable?, GameStateTable?>(current, previous);
        }
    }
}
