/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud.Client;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class GemTableUpdate : TypedRecordUpdate<Tuple<GemTable?, GemTable?>> { }

    public class GemTable : IMudTable
    {
        public readonly static TableId ID = new("", "Gem");

        public override TableId GetTableId()
        {
            return ID;
        }

        public ulong? value;

        public override Type TableType()
        {
            return typeof(GemTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(GemTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            GemTable other = (GemTable)obj;

            if (other == null)
            {
                return false;
            }
            if (value != other.value)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            value = (ulong)(int)functionParameters[0];
        }

        public override void RecordToTable(Record record)
        {
            var table = record.value;
            //bool hasValues = false;

            var valueValue = (ulong)table["value"];
            value = valueValue;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            GemTableUpdate update = (GemTableUpdate)tableUpdate;
            return update?.TypedValue.Item1;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new GemTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<GemTable?, GemTable?> MapUpdates(Tuple<Property?, Property?> value)
        {
            GemTable? current = null;
            GemTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new GemTable
                    {
                        value = value.Item1.TryGetValue("value", out var valueVal)
                            ? (ulong)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new GemTable { value = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new GemTable
                    {
                        value = value.Item2.TryGetValue("value", out var valueVal)
                            ? (ulong)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new GemTable { value = null, };
                }
            }

            return new Tuple<GemTable?, GemTable?>(current, previous);
        }
    }
}
