/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud.Client;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class HealthTableUpdate : TypedRecordUpdate<Tuple<HealthTable?, HealthTable?>> { }

    public class HealthTable : IMudTable
    {
        public readonly static TableId ID = new("", "Health");

        public override TableId GetTableId()
        {
            return ID;
        }

        public long? value;

        public override Type TableType()
        {
            return typeof(HealthTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(HealthTableUpdate);
        }

        public override void SetValues(params object[] functionParameters)
        {
            value = (long)(int)functionParameters[0];
        }

        public override void RecordToTable(Record record)
        {
            var table = record.value;
            //bool hasValues = false;

            var valueValue = (long)table["value"];
            value = valueValue;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            HealthTableUpdate update = (HealthTableUpdate)tableUpdate;
            return update?.TypedValue.Item1;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new HealthTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<HealthTable?, HealthTable?> MapUpdates(
            Tuple<Property?, Property?> value
        )
        {
            HealthTable? current = null;
            HealthTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new HealthTable
                    {
                        value = value.Item1.TryGetValue("value", out var valueVal)
                            ? (long)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new HealthTable { value = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new HealthTable
                    {
                        value = value.Item2.TryGetValue("value", out var valueVal)
                            ? (long)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new HealthTable { value = null, };
                }
            }

            return new Tuple<HealthTable?, HealthTable?>(current, previous);
        }
    }
}
