/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud.Client;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class LogTableUpdate : TypedRecordUpdate<Tuple<LogTable?, LogTable?>> { }

    public class LogTable : IMudTable
    {
        public readonly static TableId ID = new("", "Log");

        public override TableId GetTableId()
        {
            return ID;
        }

        public bool? value;

        public override Type TableType()
        {
            return typeof(LogTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(LogTableUpdate);
        }

        public override void SetValues(params object[] functionParameters)
        {
            value = (bool)functionParameters[0];
        }

        public override void RecordToTable(Record record)
        {
            var table = record.value;
            //bool hasValues = false;

            var valueValue = (bool)table["value"];
            value = valueValue;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            LogTableUpdate update = (LogTableUpdate)tableUpdate;
            return update?.TypedValue.Item1;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new LogTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<LogTable?, LogTable?> MapUpdates(Tuple<Property?, Property?> value)
        {
            LogTable? current = null;
            LogTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new LogTable
                    {
                        value = value.Item1.TryGetValue("value", out var valueVal)
                            ? (bool)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new LogTable { value = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new LogTable
                    {
                        value = value.Item2.TryGetValue("value", out var valueVal)
                            ? (bool)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new LogTable { value = null, };
                }
            }

            return new Tuple<LogTable?, LogTable?>(current, previous);
        }
    }
}
