/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud.Client;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class MapConfigTableUpdate
        : TypedRecordUpdate<Tuple<MapConfigTable?, MapConfigTable?>> { }

    public class MapConfigTable : IMudTable
    {
        public readonly static TableId ID = new("", "MapConfig");

        public override TableId GetTableId()
        {
            return ID;
        }

        public ulong? width;
        public ulong? height;
        public string? terrain;

        public override Type TableType()
        {
            return typeof(MapConfigTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(MapConfigTableUpdate);
        }

        public override void SetValues(params object[] functionParameters)
        {
            width = (ulong)(int)functionParameters[0];

            height = (ulong)(int)functionParameters[1];

            terrain = (string)functionParameters[2];
        }

        public override bool SetValues(IEnumerable<Property> result)
        {
            var hasValues = false;
            foreach (var record in result)
            {
                var attribute = record["attribute"].ToString();
                var value = record["value"];

                switch (attribute)
                {
                    case "width":
                        var widthValue = (ulong)value;
                        width = widthValue;
                        hasValues = true;
                        break;
                    case "height":
                        var heightValue = (ulong)value;
                        height = heightValue;
                        hasValues = true;
                        break;
                    case "terrain":
                        var terrainValue = (string)value;
                        terrain = terrainValue;
                        hasValues = true;
                        break;
                }
            }

            return hasValues;
        }

        public override IMudTable GetTableValue(string key)
        {
            var query = new Query()
                .Find("?value", "?attribute")
                .Where(TableId.ToString(), key, "?attribute", "?value");
            var result = NetworkManager.Instance.ds.Query(query);
            var mapConfigTable = new MapConfigTable();
            var hasValues = false;

            foreach (var record in result)
            {
                var attribute = record["attribute"].ToString();
                var value = record["value"];

                switch (attribute)
                {
                    case "width":
                        var widthValue = (ulong)value;
                        mapConfigTable.width = widthValue;
                        hasValues = true;
                        break;
                    case "height":
                        var heightValue = (ulong)value;
                        mapConfigTable.height = heightValue;
                        hasValues = true;
                        break;
                    case "terrain":
                        var terrainValue = (string)value;
                        mapConfigTable.terrain = terrainValue;
                        hasValues = true;
                        break;
                }
            }

            return hasValues ? mapConfigTable : null;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            MapConfigTableUpdate update = (MapConfigTableUpdate)tableUpdate;
            return update?.TypedValue.Item1;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new MapConfigTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<MapConfigTable?, MapConfigTable?> MapUpdates(
            Tuple<Property?, Property?> value
        )
        {
            MapConfigTable? current = null;
            MapConfigTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new MapConfigTable
                    {
                        width = value.Item1.TryGetValue("width", out var widthVal)
                            ? (ulong)widthVal
                            : default,
                        height = value.Item1.TryGetValue("height", out var heightVal)
                            ? (ulong)heightVal
                            : default,
                        terrain = value.Item1.TryGetValue("terrain", out var terrainVal)
                            ? (string)terrainVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new MapConfigTable
                    {
                        width = null,
                        height = null,
                        terrain = null,
                    };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new MapConfigTable
                    {
                        width = value.Item2.TryGetValue("width", out var widthVal)
                            ? (ulong)widthVal
                            : default,
                        height = value.Item2.TryGetValue("height", out var heightVal)
                            ? (ulong)heightVal
                            : default,
                        terrain = value.Item2.TryGetValue("terrain", out var terrainVal)
                            ? (string)terrainVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new MapConfigTable
                    {
                        width = null,
                        height = null,
                        terrain = null,
                    };
                }
            }

            return new Tuple<MapConfigTable?, MapConfigTable?>(current, previous);
        }
    }
}
