/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud.Client;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class MiliariumTableUpdate
        : TypedRecordUpdate<Tuple<MiliariumTable?, MiliariumTable?>> { }

    public class MiliariumTable : IMudTable
    {
        public readonly static TableId ID = new("", "Miliarium");

        public override TableId GetTableId()
        {
            return ID;
        }

        public bool? value;

        public override Type TableType()
        {
            return typeof(MiliariumTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(MiliariumTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            MiliariumTable other = (MiliariumTable)obj;

            if (other == null)
            {
                return false;
            }
            if (value != other.value)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            value = (bool)functionParameters[0];
        }

        public override void RecordToTable(Record record)
        {
            var table = record.value;
            //bool hasValues = false;

            var valueValue = (bool)table["value"];
            value = valueValue;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            MiliariumTableUpdate update = (MiliariumTableUpdate)tableUpdate;
            return update?.TypedValue.Item1;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new MiliariumTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<MiliariumTable?, MiliariumTable?> MapUpdates(
            Tuple<Property?, Property?> value
        )
        {
            MiliariumTable? current = null;
            MiliariumTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new MiliariumTable
                    {
                        value = value.Item1.TryGetValue("value", out var valueVal)
                            ? (bool)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new MiliariumTable { value = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new MiliariumTable
                    {
                        value = value.Item2.TryGetValue("value", out var valueVal)
                            ? (bool)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new MiliariumTable { value = null, };
                }
            }

            return new Tuple<MiliariumTable?, MiliariumTable?>(current, previous);
        }
    }
}
