/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud;
using mud.Network.schemas;
using mud;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class MoveTableUpdate : TypedRecordUpdate<Tuple<MoveTable?, MoveTable?>> { }

    public class MoveTable : IMudTable
    {
        public readonly static TableId ID = new("", "Move");

        public override TableId GetTableId()
        {
            return ID;
        }

        public ulong? value;

        public override Type TableType()
        {
            return typeof(MoveTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(MoveTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            MoveTable other = (MoveTable)obj;

            if (other == null)
            {
                return false;
            }
            if (value != other.value)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            value = (ulong)(int)functionParameters[0];
        }

        public override void RecordToTable(Record record)
        {
            var table = record.value;
            //bool hasValues = false;

            var valueValue = (ulong)table["value"];
            value = valueValue;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            MoveTableUpdate update = (MoveTableUpdate)tableUpdate;
            return update?.TypedValue.Item1;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new MoveTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<MoveTable?, MoveTable?> MapUpdates(Tuple<Property?, Property?> value)
        {
            MoveTable? current = null;
            MoveTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new MoveTable
                    {
                        value = value.Item1.TryGetValue("value", out var valueVal)
                            ? (ulong)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new MoveTable { value = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new MoveTable
                    {
                        value = value.Item2.TryGetValue("value", out var valueVal)
                            ? (ulong)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new MoveTable { value = null, };
                }
            }

            return new Tuple<MoveTable?, MoveTable?>(current, previous);
        }
    }
}
