/* Autogenerated file. Manual edits will not be saved.*/

namespace mudworld
{
    public enum ActionType
    {
        None,
        Idle,
        Dead,
        Mining,
        Shoveling,
        Stick,
        Fishing,
        Walking,
        Buy,
        Plant,
        Push,
        Chop,
        Teleport,
        Melee,
        Hop,
        Spawn,
        Bow,
        Swap,
        Pocket,
    }

    public enum TerrainType
    {
        None,
        Rock,
        Trap,
        Tree,
        HeavyBoy,
        HeavyHeavyBoy,
        Pillar,
        Road,
        Hole,
        Cursed,
    }

    public enum NPCType
    {
        None,
        Player,
        Soldier,
        Barbarian,
        Ox,
        BarbarianArcher,
        Deer,
        Taxman,
    }

    public enum RoadState
    {
        None,
        Shoveled,
        Statumen,
        Rudus,
        Nucleas,
        Paved,
        Bones,
    }

    public enum RockType
    {
        None,
        Raw,
        Statumen,
        Pavimentum,
        Rudus,
        Nucleus,
        Miliarium,
        Heavy,
        HeavyHeavy,
        Pillar,
        Statuae,
        Gremlin,
        Amphora,
    }

    public enum MoveType
    {
        None,
        Obstruction,
        Hole,
        Carry,
        Push,
        Trap,
        Permanent,
    }

    public enum FloraType
    {
        None,
        Tree,
        Oak,
        Bramble,
    }

    public enum PuzzleType
    {
        None,
        Miliarium,
        Bearer,
        Statuae,
        Count,
    }

    public enum PaymentType
    {
        None,
        Coins,
        Gems,
        Eth,
    }

    public enum ArmorSet
    {
        None,
        Armor,
        Barbarian,
        Wizard,
        Count,
    }

    public enum EffectSet
    {
        None,
        Fire,
        Sparkles,
        Water,
        Count,
    }

    public enum MaterialSet
    {
        None,
        Metal,
        Oak,
        Obsidian,
        Count,
    }

    public enum CosmeticType
    {
        None,
        Head,
        Robe,
        Effect,
        Material,
    }
}
