/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using System.Linq;
using mud;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;

namespace mudworld
{
    [System.Serializable]
    public class NameTable : MUDTable
    {
        public class NameTableUpdate : RecordUpdate
        {
            public bool? Named;
            public bool? PreviousNamed;
            public uint? First;
            public uint? PreviousFirst;
            public uint? Middle;
            public uint? PreviousMiddle;
            public uint? Last;
            public uint? PreviousLast;
        }

        public readonly static string ID = "Name";
        public static RxTable Table
        {
            get { return NetworkManager.Instance.ds.store[ID]; }
        }

        public override string GetTableId()
        {
            return ID;
        }

        public bool? Named;
        public uint? First;
        public uint? Middle;
        public uint? Last;

        public override Type TableType()
        {
            return typeof(NameTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(NameTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            NameTable other = (NameTable)obj;

            if (other == null)
            {
                return false;
            }
            if (Named != other.Named)
            {
                return false;
            }
            if (First != other.First)
            {
                return false;
            }
            if (Middle != other.Middle)
            {
                return false;
            }
            if (Last != other.Last)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            Named = (bool)functionParameters[0];

            First = (uint)functionParameters[1];

            Middle = (uint)functionParameters[2];

            Last = (uint)functionParameters[3];
        }

        public static IObservable<RecordUpdate> GetNameTableUpdates()
        {
            NameTable mudTable = new NameTable();

            return NetworkManager.Instance.sync.onUpdate
                .Where(update => update.Table.Name == ID)
                .Select(recordUpdate =>
                {
                    return mudTable.RecordUpdateToTyped(recordUpdate);
                });
        }

        public override void PropertyToTable(Property property)
        {
            Named = (bool)property["named"];
            First = (uint)property["first"];
            Middle = (uint)property["middle"];
            Last = (uint)property["last"];
        }

        public override RecordUpdate RecordUpdateToTyped(RecordUpdate recordUpdate)
        {
            var currentValue = recordUpdate.CurrentRecordValue as Property;
            var previousValue = recordUpdate.PreviousRecordValue as Property;
            bool? currentNamedTyped = null;
            bool? previousNamedTyped = null;

            if (currentValue != null && currentValue.ContainsKey("named"))
            {
                currentNamedTyped = (bool)currentValue["named"];
            }

            if (previousValue != null && previousValue.ContainsKey("named"))
            {
                previousNamedTyped = (bool)previousValue["named"];
            }
            uint? currentFirstTyped = null;
            uint? previousFirstTyped = null;

            if (currentValue != null && currentValue.ContainsKey("first"))
            {
                currentFirstTyped = (uint)currentValue["first"];
            }

            if (previousValue != null && previousValue.ContainsKey("first"))
            {
                previousFirstTyped = (uint)previousValue["first"];
            }
            uint? currentMiddleTyped = null;
            uint? previousMiddleTyped = null;

            if (currentValue != null && currentValue.ContainsKey("middle"))
            {
                currentMiddleTyped = (uint)currentValue["middle"];
            }

            if (previousValue != null && previousValue.ContainsKey("middle"))
            {
                previousMiddleTyped = (uint)previousValue["middle"];
            }
            uint? currentLastTyped = null;
            uint? previousLastTyped = null;

            if (currentValue != null && currentValue.ContainsKey("last"))
            {
                currentLastTyped = (uint)currentValue["last"];
            }

            if (previousValue != null && previousValue.ContainsKey("last"))
            {
                previousLastTyped = (uint)previousValue["last"];
            }

            return new NameTableUpdate
            {
                Table = recordUpdate.Table,
                CurrentRecordValue = recordUpdate.CurrentRecordValue,
                PreviousRecordValue = recordUpdate.PreviousRecordValue,
                CurrentRecordKey = recordUpdate.CurrentRecordKey,
                PreviousRecordKey = recordUpdate.PreviousRecordKey,
                Type = recordUpdate.Type,
                Named = currentNamedTyped,
                PreviousNamed = previousNamedTyped,
                First = currentFirstTyped,
                PreviousFirst = previousFirstTyped,
                Middle = currentMiddleTyped,
                PreviousMiddle = previousMiddleTyped,
                Last = currentLastTyped,
                PreviousLast = previousLastTyped,
            };
        }
    }
}
