/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud;
using mud.Network.schemas;
using mud;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class NPCTableUpdate : TypedRecordUpdate<Tuple<NPCTable?, NPCTable?>> { }

    public class NPCTable : IMudTable
    {
        public readonly static TableId ID = new("", "NPC");

        public override TableId GetTableId()
        {
            return ID;
        }

        public ulong? value;

        public override Type TableType()
        {
            return typeof(NPCTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(NPCTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            NPCTable other = (NPCTable)obj;

            if (other == null)
            {
                return false;
            }
            if (value != other.value)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            value = (ulong)(int)functionParameters[0];
        }

        public override void RecordToTable(Record record)
        {
            var table = record.value;
            //bool hasValues = false;

            var valueValue = (ulong)table["value"];
            value = valueValue;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            NPCTableUpdate update = (NPCTableUpdate)tableUpdate;
            return update?.TypedValue.Item1;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new NPCTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<NPCTable?, NPCTable?> MapUpdates(Tuple<Property?, Property?> value)
        {
            NPCTable? current = null;
            NPCTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new NPCTable
                    {
                        value = value.Item1.TryGetValue("value", out var valueVal)
                            ? (ulong)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new NPCTable { value = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new NPCTable
                    {
                        value = value.Item2.TryGetValue("value", out var valueVal)
                            ? (ulong)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new NPCTable { value = null, };
                }
            }

            return new Tuple<NPCTable?, NPCTable?>(current, previous);
        }
    }
}
