/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud;
using mud.Network.schemas;
using mud;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class OxTableUpdate : TypedRecordUpdate<Tuple<OxTable?, OxTable?>> { }

    public class OxTable : IMudTable
    {
        public readonly static TableId ID = new("", "Ox");

        public override TableId GetTableId()
        {
            return ID;
        }

        public bool? value;

        public override Type TableType()
        {
            return typeof(OxTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(OxTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            OxTable other = (OxTable)obj;

            if (other == null)
            {
                return false;
            }
            if (value != other.value)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            value = (bool)functionParameters[0];
        }

        public override void RecordToTable(Record record)
        {
            var table = record.value;
            //bool hasValues = false;

            var valueValue = (bool)table["value"];
            value = valueValue;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            OxTableUpdate update = (OxTableUpdate)tableUpdate;
            return update?.TypedValue.Item1;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new OxTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<OxTable?, OxTable?> MapUpdates(Tuple<Property?, Property?> value)
        {
            OxTable? current = null;
            OxTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new OxTable
                    {
                        value = value.Item1.TryGetValue("value", out var valueVal)
                            ? (bool)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new OxTable { value = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new OxTable
                    {
                        value = value.Item2.TryGetValue("value", out var valueVal)
                            ? (bool)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new OxTable { value = null, };
                }
            }

            return new Tuple<OxTable?, OxTable?>(current, previous);
        }
    }
}
