/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;

namespace mudworld
{
    public class PuzzleTable : IMudTable
    {
        public class PuzzleTableUpdate : RecordUpdate
        {
            public int? PuzzleType;
            public int? PreviousPuzzleType;
            public bool? Complete;
            public bool? PreviousComplete;
        }

        public readonly static string ID = "Puzzle";
        public static RxTable Table
        {
            get { return NetworkManager.Instance.ds.store[ID]; }
        }

        public override string GetTableId()
        {
            return ID;
        }

        public int? PuzzleType;
        public bool? Complete;

        public override Type TableType()
        {
            return typeof(PuzzleTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(PuzzleTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            PuzzleTable other = (PuzzleTable)obj;

            if (other == null)
            {
                return false;
            }
            if (PuzzleType != other.PuzzleType)
            {
                return false;
            }
            if (Complete != other.Complete)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            PuzzleType = (int)functionParameters[0];

            Complete = (bool)functionParameters[1];
        }

        public static IObservable<RecordUpdate> GetPuzzleTableUpdates()
        {
            PuzzleTable mudTable = new PuzzleTable();

            return NetworkManager.Instance.sync.onUpdate
                .Where(update => update.Table.Name == ID)
                .Select(recordUpdate =>
                {
                    return mudTable.RecordUpdateToTyped(recordUpdate);
                });
        }

        public override void PropertyToTable(Property property)
        {
            PuzzleType = (int)property["puzzleType"];
            Complete = (bool)property["complete"];
        }

        public override RecordUpdate RecordUpdateToTyped(RecordUpdate recordUpdate)
        {
            var currentValue = recordUpdate.CurrentRecordValue as Property;
            var previousValue = recordUpdate.PreviousRecordValue as Property;
            int? currentPuzzleTypeTyped = null;
            int? previousPuzzleTypeTyped = null;

            if (currentValue != null && currentValue.ContainsKey("puzzletype"))
            {
                currentPuzzleTypeTyped = (int)currentValue["puzzletype"];
            }

            if (previousValue != null && previousValue.ContainsKey("puzzletype"))
            {
                previousPuzzleTypeTyped = (int)previousValue["puzzletype"];
            }
            bool? currentCompleteTyped = null;
            bool? previousCompleteTyped = null;

            if (currentValue != null && currentValue.ContainsKey("complete"))
            {
                currentCompleteTyped = (bool)currentValue["complete"];
            }

            if (previousValue != null && previousValue.ContainsKey("complete"))
            {
                previousCompleteTyped = (bool)previousValue["complete"];
            }

            return new PuzzleTableUpdate
            {
                Table = recordUpdate.Table,
                CurrentRecordValue = recordUpdate.CurrentRecordValue,
                PreviousRecordValue = recordUpdate.PreviousRecordValue,
                CurrentRecordKey = recordUpdate.CurrentRecordKey,
                PreviousRecordKey = recordUpdate.PreviousRecordKey,
                Type = recordUpdate.Type,
                PuzzleType = currentPuzzleTypeTyped,
                PreviousPuzzleType = previousPuzzleTypeTyped,
                Complete = currentCompleteTyped,
                PreviousComplete = previousCompleteTyped,
            };
        }
    }
}
