/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud.Client;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class RoadTableUpdate : TypedRecordUpdate<Tuple<RoadTable?, RoadTable?>> { }

    public class RoadTable : IMudTable
    {
        public readonly static TableId ID = new("", "Road");

        public override TableId GetTableId()
        {
            return ID;
        }

        public ulong? state;
        public string? filled;

        public override Type TableType()
        {
            return typeof(RoadTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(RoadTableUpdate);
        }

        public override void SetValues(params object[] functionParameters)
        {
            state = (ulong)(int)functionParameters[0];

            filled = (string)functionParameters[1];
        }

        public override bool SetValues(IEnumerable<Property> result)
        {
            var hasValues = false;
            foreach (var record in result)
            {
                var attribute = record["attribute"].ToString();
                var value = record["value"];

                switch (attribute)
                {
                    case "state":
                        var stateValue = (ulong)value;
                        state = stateValue;
                        hasValues = true;
                        break;
                    case "filled":
                        var filledValue = (string)value;
                        filled = filledValue;
                        hasValues = true;
                        break;
                }
            }

            return hasValues;
        }

        public override IMudTable GetTableValue(string key)
        {
            var query = new Query()
                .Find("?value", "?attribute")
                .Where(TableId.ToString(), key, "?attribute", "?value");
            var result = NetworkManager.Instance.ds.Query(query);
            var roadTable = new RoadTable();
            var hasValues = false;

            foreach (var record in result)
            {
                var attribute = record["attribute"].ToString();
                var value = record["value"];

                switch (attribute)
                {
                    case "state":
                        var stateValue = (ulong)value;
                        roadTable.state = stateValue;
                        hasValues = true;
                        break;
                    case "filled":
                        var filledValue = (string)value;
                        roadTable.filled = filledValue;
                        hasValues = true;
                        break;
                }
            }

            return hasValues ? roadTable : null;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            RoadTableUpdate update = (RoadTableUpdate)tableUpdate;
            return update?.TypedValue.Item1;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new RoadTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<RoadTable?, RoadTable?> MapUpdates(Tuple<Property?, Property?> value)
        {
            RoadTable? current = null;
            RoadTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new RoadTable
                    {
                        state = value.Item1.TryGetValue("state", out var stateVal)
                            ? (ulong)stateVal
                            : default,
                        filled = value.Item1.TryGetValue("filled", out var filledVal)
                            ? (string)filledVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new RoadTable { state = null, filled = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new RoadTable
                    {
                        state = value.Item2.TryGetValue("state", out var stateVal)
                            ? (ulong)stateVal
                            : default,
                        filled = value.Item2.TryGetValue("filled", out var filledVal)
                            ? (string)filledVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new RoadTable { state = null, filled = null, };
                }
            }

            return new Tuple<RoadTable?, RoadTable?>(current, previous);
        }
    }
}
