/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud.Client;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class RobeTableUpdate : TypedRecordUpdate<Tuple<RobeTable?, RobeTable?>> { }

    public class RobeTable : IMudTable
    {
        public readonly static TableId ID = new("", "Robe");

        public override TableId GetTableId()
        {
            return ID;
        }

        public long? value;

        public override Type TableType()
        {
            return typeof(RobeTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(RobeTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            RobeTable other = (RobeTable)obj;

            if (other == null)
            {
                return false;
            }
            if (value != other.value)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            value = (long)(int)functionParameters[0];
        }

        public override void RecordToTable(Record record)
        {
            var table = record.value;
            //bool hasValues = false;

            var valueValue = (long)table["value"];
            value = valueValue;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            RobeTableUpdate update = (RobeTableUpdate)tableUpdate;
            return update?.TypedValue.Item1;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new RobeTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<RobeTable?, RobeTable?> MapUpdates(Tuple<Property?, Property?> value)
        {
            RobeTable? current = null;
            RobeTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new RobeTable
                    {
                        value = value.Item1.TryGetValue("value", out var valueVal)
                            ? (long)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new RobeTable { value = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new RobeTable
                    {
                        value = value.Item2.TryGetValue("value", out var valueVal)
                            ? (long)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new RobeTable { value = null, };
                }
            }

            return new Tuple<RobeTable?, RobeTable?>(current, previous);
        }
    }
}
