/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using System.Linq;
using mud;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;

namespace mudworld
{
    public class RobeTable : MUDTable
    {
        public class RobeTableUpdate : RecordUpdate
        {
            public bool[]? Value;
            public bool[]? PreviousValue;
        }

        public readonly static string ID = "Robe";
        public static RxTable Table
        {
            get { return NetworkManager.Instance.ds.store[ID]; }
        }

        public override string GetTableId()
        {
            return ID;
        }

        public bool[]? Value;

        public override Type TableType()
        {
            return typeof(RobeTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(RobeTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            RobeTable other = (RobeTable)obj;

            if (other == null)
            {
                return false;
            }
            if (Value != other.Value)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            Value = (bool[])functionParameters[0];
        }

        public static IObservable<RecordUpdate> GetRobeTableUpdates()
        {
            RobeTable mudTable = new RobeTable();

            return NetworkManager.Instance.sync.onUpdate
                .Where(update => update.Table.Name == ID)
                .Select(recordUpdate =>
                {
                    return mudTable.RecordUpdateToTyped(recordUpdate);
                });
        }

        public override void PropertyToTable(Property property)
        {
            Value = ((object[])property["value"]).Cast<bool>().ToArray();
        }

        public override RecordUpdate RecordUpdateToTyped(RecordUpdate recordUpdate)
        {
            var currentValue = recordUpdate.CurrentRecordValue as Property;
            var previousValue = recordUpdate.PreviousRecordValue as Property;
            bool[]? currentValueTyped = null;
            bool[]? previousValueTyped = null;

            if (currentValue != null && currentValue.ContainsKey("value"))
            {
                currentValueTyped = ((object[])currentValue["value"]).Cast<bool>().ToArray();
            }

            if (previousValue != null && previousValue.ContainsKey("value"))
            {
                previousValueTyped = ((object[])previousValue["value"]).Cast<bool>().ToArray();
            }

            return new RobeTableUpdate
            {
                Table = recordUpdate.Table,
                CurrentRecordValue = recordUpdate.CurrentRecordValue,
                PreviousRecordValue = recordUpdate.PreviousRecordValue,
                CurrentRecordKey = recordUpdate.CurrentRecordKey,
                PreviousRecordKey = recordUpdate.PreviousRecordKey,
                Type = recordUpdate.Type,
                Value = currentValueTyped,
                PreviousValue = previousValueTyped,
            };
        }
    }
}
