/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud.Client;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class RowTableUpdate : TypedRecordUpdate<Tuple<RowTable?, RowTable?>> { }

    public class RowTable : IMudTable
    {
        public readonly static TableId ID = new("", "Row");

        public override TableId GetTableId()
        {
            return ID;
        }

        public long? value;

        public override Type TableType()
        {
            return typeof(RowTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(RowTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            RowTable other = (RowTable)obj;

            if (other == null)
            {
                return false;
            }
            if (value != other.value)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            value = (long)(int)functionParameters[0];
        }

        public override void RecordToTable(Record record)
        {
            var table = record.value;
            //bool hasValues = false;

            var valueValue = (long)table["value"];
            value = valueValue;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            RowTableUpdate update = (RowTableUpdate)tableUpdate;
            return update?.TypedValue.Item1;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new RowTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<RowTable?, RowTable?> MapUpdates(Tuple<Property?, Property?> value)
        {
            RowTable? current = null;
            RowTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new RowTable
                    {
                        value = value.Item1.TryGetValue("value", out var valueVal)
                            ? (long)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new RowTable { value = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new RowTable
                    {
                        value = value.Item2.TryGetValue("value", out var valueVal)
                            ? (long)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new RowTable { value = null, };
                }
            }

            return new Tuple<RowTable?, RowTable?>(current, previous);
        }
    }
}
