/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class ShovelTableUpdate : TypedRecordUpdate<Tuple<ShovelTable?, ShovelTable?>> { }

    public class ShovelTable : IMudTable
    {
        public readonly static TableId ID = new("", "Shovel");

        public override TableId GetTableId()
        {
            return ID;
        }

        public bool? value;

        public override Type TableType()
        {
            return typeof(ShovelTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(ShovelTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            ShovelTable other = (ShovelTable)obj;

            if (other == null)
            {
                return false;
            }
            if (value != other.value)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            value = (bool)functionParameters[0];
        }

        public override void RecordToTable(Record record)
        {
            var table = record.value;
            //bool hasValues = false;

            var valueValue = (bool)table["value"];
            value = valueValue;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            ShovelTableUpdate update = (ShovelTableUpdate)tableUpdate;
            return update?.TypedValue.Item1;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new ShovelTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<ShovelTable?, ShovelTable?> MapUpdates(
            Tuple<Property?, Property?> value
        )
        {
            ShovelTable? current = null;
            ShovelTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new ShovelTable
                    {
                        value = value.Item1.TryGetValue("value", out var valueVal)
                            ? (bool)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new ShovelTable { value = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new ShovelTable
                    {
                        value = value.Item2.TryGetValue("value", out var valueVal)
                            ? (bool)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new ShovelTable { value = null, };
                }
            }

            return new Tuple<ShovelTable?, ShovelTable?>(current, previous);
        }
    }
}
