/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud;
using mud.Network.schemas;
using mud;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class SoldierTableUpdate : TypedRecordUpdate<Tuple<SoldierTable?, SoldierTable?>> { }

    public class SoldierTable : IMudTable
    {
        public readonly static TableId ID = new("", "Soldier");

        public override TableId GetTableId()
        {
            return ID;
        }

        public bool? value;

        public override Type TableType()
        {
            return typeof(SoldierTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(SoldierTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            SoldierTable other = (SoldierTable)obj;

            if (other == null)
            {
                return false;
            }
            if (value != other.value)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            value = (bool)functionParameters[0];
        }

        public override void RecordToTable(Record record)
        {
            var table = record.value;
            //bool hasValues = false;

            var valueValue = (bool)table["value"];
            value = valueValue;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            SoldierTableUpdate update = (SoldierTableUpdate)tableUpdate;
            return update?.TypedValue.Item1;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new SoldierTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<SoldierTable?, SoldierTable?> MapUpdates(
            Tuple<Property?, Property?> value
        )
        {
            SoldierTable? current = null;
            SoldierTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new SoldierTable
                    {
                        value = value.Item1.TryGetValue("value", out var valueVal)
                            ? (bool)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new SoldierTable { value = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new SoldierTable
                    {
                        value = value.Item2.TryGetValue("value", out var valueVal)
                            ? (bool)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new SoldierTable { value = null, };
                }
            }

            return new Tuple<SoldierTable?, SoldierTable?>(current, previous);
        }
    }
}
