/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud.Client;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class TokenTableUpdate : TypedRecordUpdate<Tuple<TokenTable?, TokenTable?>> { }

    public class TokenTable : IMudTable
    {
        public readonly static TableId ID = new("", "Token");

        public override TableId GetTableId()
        {
            return ID;
        }

        public System.Numerics.BigInteger? value;

        public override Type TableType()
        {
            return typeof(TokenTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(TokenTableUpdate);
        }

        public override void SetValues(params object[] functionParameters)
        {
            value = (System.Numerics.BigInteger)functionParameters[0];
        }

        public override bool SetValues(IEnumerable<Property> result)
        {
            var hasValues = false;
            foreach (var record in result)
            {
                var attribute = record["attribute"].ToString();
                var value = record["value"];

                switch (attribute)
                {
                    case "value":
                        var valueValue = new System.Numerics.BigInteger((int)value);
                        value = valueValue;
                        hasValues = true;
                        break;
                }
            }

            return hasValues;
        }

        public override IMudTable GetTableValue(string key)
        {
            var query = new Query()
                .Find("?value", "?attribute")
                .Where(TableId.ToString(), key, "?attribute", "?value");
            var result = NetworkManager.Instance.ds.Query(query);
            var tokenTable = new TokenTable();
            var hasValues = false;

            foreach (var record in result)
            {
                var attribute = record["attribute"].ToString();
                var value = record["value"];

                switch (attribute)
                {
                    case "value":
                        var valueValue = new System.Numerics.BigInteger((int)value);
                        tokenTable.value = valueValue;
                        hasValues = true;
                        break;
                }
            }

            return hasValues ? tokenTable : null;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            TokenTableUpdate update = (TokenTableUpdate)tableUpdate;
            return update?.TypedValue.Item1;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new TokenTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<TokenTable?, TokenTable?> MapUpdates(Tuple<Property?, Property?> value)
        {
            TokenTable? current = null;
            TokenTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new TokenTable
                    {
                        value = value.Item1.TryGetValue("value", out var valueVal)
                            ? (System.Numerics.BigInteger)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new TokenTable { value = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new TokenTable
                    {
                        value = value.Item2.TryGetValue("value", out var valueVal)
                            ? (System.Numerics.BigInteger)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new TokenTable { value = null, };
                }
            }

            return new Tuple<TokenTable?, TokenTable?>(current, previous);
        }
    }
}
