/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud.Client;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class TriggerTableUpdate : TypedRecordUpdate<Tuple<TriggerTable?, TriggerTable?>> { }

    public class TriggerTable : IMudTable
    {
        public readonly static TableId ID = new("", "Trigger");

        public override TableId GetTableId()
        {
            return ID;
        }

        public string? value;

        public override Type TableType()
        {
            return typeof(TriggerTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(TriggerTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            TriggerTable other = (TriggerTable)obj;

            if (other == null)
            {
                return false;
            }
            if (value != other.value)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters)
        {
            value = (string)functionParameters[0];
        }

        public override void RecordToTable(Record record)
        {
            var table = record.value;
            //bool hasValues = false;

            var valueValue = (string)table["value"];
            value = valueValue;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            TriggerTableUpdate update = (TriggerTableUpdate)tableUpdate;
            return update?.TypedValue.Item1;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new TriggerTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<TriggerTable?, TriggerTable?> MapUpdates(
            Tuple<Property?, Property?> value
        )
        {
            TriggerTable? current = null;
            TriggerTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new TriggerTable
                    {
                        value = value.Item1.TryGetValue("value", out var valueVal)
                            ? (string)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new TriggerTable { value = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new TriggerTable
                    {
                        value = value.Item2.TryGetValue("value", out var valueVal)
                            ? (string)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new TriggerTable { value = null, };
                }
            }

            return new Tuple<TriggerTable?, TriggerTable?>(current, previous);
        }
    }
}
