// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { MapConfig, MapConfigTableId } from "./tables/MapConfig.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
import { Shovel, ShovelTableId } from "./tables/Shovel.sol";
import { Pickaxe, PickaxeTableId } from "./tables/Pickaxe.sol";
import { Rock, RockData, RockTableId } from "./tables/Rock.sol";
import { Road, RoadTableId } from "./tables/Road.sol";
import { Damage, DamageTableId } from "./tables/Damage.sol";
import { Health, HealthTableId } from "./tables/Health.sol";
import { Obstruction, ObstructionTableId } from "./tables/Obstruction.sol";
import { Shovelable, ShovelableTableId } from "./tables/Shovelable.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
