// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { GameConfig, GameConfigData, GameConfigTableId } from "./tables/GameConfig.sol";
import { Stats, StatsTableId } from "./tables/Stats.sol";
import { MapConfig, MapConfigTableId } from "./tables/MapConfig.sol";
import { Bounds, BoundsTableId } from "./tables/Bounds.sol";
import { RoadConfig, RoadConfigTableId } from "./tables/RoadConfig.sol";
import { GameState, GameStateTableId } from "./tables/GameState.sol";
import { Chunk, ChunkData, ChunkTableId } from "./tables/Chunk.sol";
import { Row, RowTableId } from "./tables/Row.sol";
import { Shovel, ShovelTableId } from "./tables/Shovel.sol";
import { Pickaxe, PickaxeTableId } from "./tables/Pickaxe.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
import { State, StateTableId } from "./tables/State.sol";
import { Move, MoveTableId } from "./tables/Move.sol";
import { Carrying, CarryingTableId } from "./tables/Carrying.sol";
import { Pavement, PavementTableId } from "./tables/Pavement.sol";
import { Damage, DamageTableId } from "./tables/Damage.sol";
import { Health, HealthTableId } from "./tables/Health.sol";
import { Infinite, InfiniteTableId } from "./tables/Infinite.sol";
import { Rock, RockTableId } from "./tables/Rock.sol";
import { Road, RoadTableId } from "./tables/Road.sol";
import { Tree, TreeTableId } from "./tables/Tree.sol";
