// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMoveSystem {
  function push(int32 x, int32 y, int32 pushX, int32 pushY) external;

  function moveFrom(int32 x, int32 y) external;

  function move(int32 x, int32 y) external;

  function spawn(int32 x, int32 y) external;
}
