namespace CraftingAnims
{
    /// <summary>
    /// Enum to use with the "Action" parameter of the animator. Convert to (int) to set.
	/// TriggerNumber is always -1 for future use with RPG Animation Pack.
    /// </summary>
    public enum CrafterAnimatorTriggers
    {
        NoAction = 0,
        CarryPickupTrigger = 1,
        CarryRecieveTrigger = 2,
        CarryHandoffTrigger = 3,
        CarryPutdownTrigger = 4,
        CarryThrowTrigger = 5,
        ItemBeltTrigger = 6,
        ItemBackTrigger = 7,
        ItemPickupTrigger = 8,
        ItemPullUpTrigger = 9,
        ItemTakeTrigger = 10,
        ItemRecieveTrigger = 11,
        ItemHandoffTrigger = 12,
        ItemBeltAwayTrigger = 13,
        ItemPutdownTrigger = 14,
        ItemDropTrigger = 15,
        ItemBackAwayTrigger = 16,
        ItemPlantTrigger = 17,
        ChoppingStartTrigger = 18,
        ChopVerticalTrigger = 19,
        ChopHorizontalTrigger = 20,
        ChopDiagonalTrigger = 21,
        ChopFinishTrigger = 22,
        ChopCeilingTrigger = 23,
        ChopGroundTrigger = 24,
        DiggingStartTrigger = 25,
        DiggingScoopTrigger = 26,
        DiggingFinishTrigger = 27,
        FishingCastTrigger = 28,
		FishingReelTrigger = 29,
		FishingFinishTrigger = 30,
		SawStartTrigger = 31,
		SawFinishTrigger = 32,
		HammerWallTrigger = 33,
		HammerTableTrigger = 34,
		ItemEatTrigger = 35,
		ItemDrinkTrigger = 36,
		ItemWaterTrigger = 37,
		ItemSickleUseTrigger = 38,
		ItemRakeUseTrigger = 39,
		ChairSitTrigger = 40,
		ChairTalk1Trigger = 41,
		ChairEatTrigger = 42,
		ChairDrinkTrigger = 43,
		ChairStandTrigger = 44,
		GatherTrigger = 45,
		Bored1Trigger = 46,
		ClimbStartTrigger = 47,
		ClimbOffBottomTrigger = 48,
		PushPullStartTrigger = 49,
		PushPullReleaseTrigger = 50,
		ClimbOnTopTrigger = 51,
		ChopVerticalUpperTrigger = 52,
		ChopHorizontalUpperTrigger = 53,
		EatUpperTrigger = 54,
		DrinkUpperTrigger = 55,
		Cheer1Trigger = 56,
		Cheer2Trigger = 57,
		Cheer3Trigger = 58,
		Wave1Trigger = 59,
		GatherKneelingTrigger = 60,
		LumberPickupTrigger = 61,
		CarryOverheadPickupTrigger = 62,
		CarryOverheadThrowTrigger = 63,
		PrayDownTrigger = 64,
		PrayStandTrigger = 65,
		FearTrigger = 66,
		CartPullGrabTrigger = 67,
		CartPullReleaseTrigger = 68,
		ItemKneelDownTrigger = 69,
		ItemKneelStandTrigger = 70,
		ItemKneelHammerTrigger = 71,
		ItemChiselTrigger = 72,
		ItemPaintTrigger = 73,
		ItemPaintRefillTrigger = 74,
		LaydownLaydownTrigger = 75,
		LaydownGetupTrigger = 76,
		CrawlStartTrigger = 77,
		CrawlGetupTrigger = 78,
		SpearfishStartTrigger = 79,
		SpearfishAttackTrigger = 80,
		SpearfishEndTrigger = 81,
		ClimbUpTrigger = 82,
		ClimbDownTrigger = 83,
		ClimbOffTopTrigger = 84,
		CarryOverheadPutdownTrigger = 85,
		ItemSwingHorizontal = 86,
		ItemSwingVertical = 87
	}
}