using System.Collections;
using System.Collections.Generic;
using UnityEngine;


public class AISegmentation : MonoBehaviour
{
    public static bool On = false;
    public Segmentation segment;
    [Header("Debug")]
    public Color color;
    public Renderer [] renderers;

    void Start() {

        if(!On)
            return;
        
        renderers = GetComponentsInChildren<Renderer>(true);
        MaterialPropertyBlock mpb = new MaterialPropertyBlock();
        
        if(segmentationMaterial == null) {
            segmentationMaterial = new Material(Shader.Find("Universal Render Pipeline/Unlit"));
            Camera.main.backgroundColor = IDToColor(Segmentation.sky);
        }

        color = IDToColor(segment);
        for(int i = 0; i < renderers.Length; i++) {

            Material[] sharedMaterialsCopy = renderers[i].sharedMaterials;

            for(int j = 0; j < sharedMaterialsCopy.Length; j++) {
                sharedMaterialsCopy[j] = segmentationMaterial;
            }

            renderers[i].sharedMaterials = sharedMaterialsCopy;
            
            mpb.SetColor("_BaseColor", color);
            renderers[i].SetPropertyBlock(mpb);

        }
    }
    public Color IDToColor(Segmentation segmentation) {
        Color color = new Color();
        ColorUtility.TryParseHtmlString(Colors[(int)segment], out color);
        return color;
    }
    public static Material segmentationMaterial;
    public static List<string> Colors = new List<string> {
"#787878",
"#B47878",
"#06E6E6",
"#503232",
"#04C803",
"#787850",
"#8C8C8C",
"#CC05FF",
"#E6E6E6",
"#04FA07",
"#E005FF",
"#EBFF07",
"#96053D",
"#787846",
"#08FF33",
"#FF0652",
"#8FFF8C",
"#CCFF04",
"#FF3307",
"#CC4603",
"#0066C8",
"#3DE6FA",
"#FF0633",
"#0B66FF",
"#FF0747",
"#FF09E0",
"#0907E6",
"#DCDCDC",
"#FF095C",
"#7009FF",
"#08FFD6",
"#07FFE0",
"#FFB806",
"#0AFF47",
"#FF290A",
"#07FFFF",
"#E0FF08",
"#6608FF",
"#FF3D06",
"#FFC207",
"#FF7A08",
"#00FF14",
"#FF0829",
"#FF0599",
"#0633FF",
"#EB0CFF",
"#A09614",
"#00A3FF",
"#8C8C8C",
"#FA0A0F",
"#14FF00",
"#1FFF00",
"#FF1F00",
"#FFE000",
"#99FF00",
"#0000FF",
"#FF4700",
"#00EBFF",
"#00ADFF",
"#1F00FF",
"#0BC8C8",
"#FF5200",
"#00FFF5",
"#003DFF",
"#00FF70",
"#00FF85",
"#FF0000",
"#FFA300",
"#FF6600",
"#C2FF00",
"#008FFF",
"#33FF00",
"#0052FF",
"#00FF29",
"#00FFAD",
"#0A00FF",
"#ADFF00",
"#00FF99",
"#FF5C00",
"#FF00FF",
"#FF00F5",
"#FF0066",
"#FFAD00",
"#FF0014",
"#FFB8B8",
"#001FFF",
"#00FF3D",
"#0047FF",
"#FF00CC",
"#00FFC2",
"#00FF52",
"#000AFF",
"#0070FF",
"#3300FF",
"#00C2FF",
"#007AFF",
"#00FFA3",
"#FF9900",
"#00FF0A",
"#FF7000",
"#8FFF00",
"#5200FF",
"#A3FF00",
"#FFEB00",
"#08B8AA",
"#8500FF",
"#00FF5C",
"#B800FF",
"#FF001F",
"#00B8FF",
"#00D6FF",
"#FF0070",
"#5CFF00",
"#00E0FF",
"#70E0FF",
"#46B8A0",
"#A300FF",
"#9900FF",
"#47FF00",
"#FF00A3",
"#FFCC00",
"#FF008F",
"#00FFEB",
"#85FF00",
"#FF00EB",
"#F500FF",
"#FF007A",
"#FFF500",
"#0ABED4",
"#D6FF00",
"#00CCFF",
"#1400FF",
"#FFFF00",
"#0099FF",
"#0029FF",
"#00FFCC",
"#2900FF",
"#29FF00",
"#AD00FF",
"#00F5FF",
"#4700FF",
"#7A00FF",
"#00FFB8",
"#005CFF",
"#B8FF00",
"#0085FF",
"#FFD600",
"#19C2C2",
"#66FF00",
"#5C00FF"
};

}


public enum Segmentation
{
    wall,
    building_edifice,
    sky,
    floor_flooring,
    tree,
    ceiling,
    road_route,
    bed,
    windowpane_window,
    grass,
    cabinet,
    sidewalk_pavement,
    person_individual_someone_somebody_mortal_soul,
    earth_ground,
    door_double_door,
    table,
    mountain_mount,
    plant_flora_plant_life,
    curtain_drape_drapery_mantle_pall,
    chair,
    car_auto_automobile_machine_motorcar,
    water,
    painting_picture,
    sofa_couch_lounge,
    shelf,
    house,
    sea,
    mirror,
    rug_carpet_carpeting,
    field,
    armchair,
    seat,
    fence_fencing,
    desk,
    rock_stone,
    wardrobe_closet_press,
    lamp,
    bathtub_bathing_tub_bath_tub,
    railing_rail,
    cushion,
    base_pedestal_stand,
    box,
    column_pillar,
    signboard_sign,
    chest_of_drawers_chest_bureau_dresser,
    counter,
    sand,
    sink,
    skyscraper,
    fireplace_hearth_open_fireplace,
    refrigerator_icebox,
    grandstand_covered_stand,
    path,
    stairs_steps,
    runway,
    case_display_case_showcase_vitrine,
    pool_table_billiard_table_snooker_table,
    pillow,
    screen_door_screen,
    stairway_staircase,
    river,
    bridge_span,
    bookcase,
    blind_screen,
    coffee_table_cocktail_table,
    toilet_can_commode_crapper_pot_potty_stool_throne,
    flower,
    book,
    hill,
    bench,
    countertop,
    stove_kitchen_stove_range_kitchen_range_cooking_stove,
    palm_palm_tree,
    kitchen_island,
    computer_computing_machine_computing_device_data_processor_electronic_computer_information_processing_system,
    swivel_chair,
    boat,
    bar,
    arcade_machine,
    hovel_hut_hutch_shack_shanty,
    bus_autobus_coach_charabanc_double_decker_jitney_motorbus_motorcoach_omnibus_passenger_vehicle,
    towel,
    light_light_source,
    truck_motortruck,
    tower,
    chandelier_pendant_pendent,
    awning_sunshade_sunblind,
    streetlight_street_lamp,
    booth_cubicle_stall_kiosk,
    television_television_receiver_television_set_tv_tv_set_idiot_box_boob_tube_telly_goggle_box,
    airplane_aeroplane_plane,
    dirt_track,
    apparel_wearing_apparel_dress_clothes,
    pole,
    land_ground_soil,
    bannister_banister_balustrade_balusters_handrail,
    escalator_moving_staircase_moving_stairway,
    ottoman_pouf_pouffe_puff_hassock,
    bottle,
    buffet_counter_sideboard,
    poster_posting_placard_notice_bill_card,
    stage,
    van,
    ship,
    fountain,
    conveyer_belt_conveyor_belt_conveyer_conveyor_transporter,
    canopy,
    washer_automatic_washer_washing_machine,
    plaything_toy,
    swimming_pool_swimming_bath_natatorium,
    stool,
    barrel_cask,
    basket_handbasket,
    waterfall_falls,
    tent_collapsible_shelter,
    bag,
    minibike_motorbike,
    cradle,
    oven,
    ball,
    food_solid_food,
    step_stair,
    tank_storage_tank,
    trade_name_brand_name_brand_marque,
    microwave_microwave_oven,
    pot_flowerpot,
    animal_animate_being_beast_brute_creature_fauna,
    bicycle_bike_wheel_cycle,
    lake,
    dishwasher_dish_washer_dishwashing_machine,
    screen_silver_screen_projection_screen,
    blanket_cover,
    sculpture,
    hood_exhaust_hood,
    sconce,
    vase,
    traffic_light_traffic_signal_stoplight,
    tray,
    ashcan_trash_can_garbage_can_wastebin_ash_bin_ash_bin_ashbin_dustbin_trash_barrel_trash_bin,
    fan,
    pier_wharf_wharfage_dock,
    crt_screen,
    plate,
    monitor_monitoring_device,
    bulletin_board_notice_board,
    shower,
    radiator,
    glass_drinking_glass,
    clock,
    flag
}
